### ISSUE TITLE
Docker version cannot connect to Ollama dockerized

### ISSUE THREAD

**Issue by alexandervnuchkov** [ruecat/ollama-telegram#29]
Not sure, but it looks like the bot Docker version does not respect the base URL setting in the `.env` file. It shows the following lines and crashes, no matter what settings I use for the `OLLAMA_BASE_URL` variable:

```bash
ollama-telegram  | DEBUG:httpcore.connection:connect_tcp.started host='127.0.0.1' port=11434 local_address=None timeout=None socket_options=None
ollama-telegram  | DEBUG:httpcore.connection:connect_tcp.failed exception=ConnectError(ConnectionRefusedError(111, 'Connection refused'))
```

The `OLLAMA_BASE_URL` variable in the `.env` file:

```plaintext
OLLAMA_BASE_URL=ollama-server
```

My `docker-compose.yml` contents:

```yaml
name: ollama
services:
  ollama-server:
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434
    container_name: ollama-server
    restart: always
    image: ollama/ollama
  ollama-telegram:
    image: ruecat/ollama-telegram
    container_name: ollama-telegram
    restart: always
    env_file:
      - .env
```

**Comment by ruecat** [comment]
I see the problem. You have to set port for telegram client as well + same network.
Try using this:
```yaml
name: ollama
services:
  ollama-server:
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    networks:
      - neurolab
  ollama-telegram:
    restart: always
    image: ruecat/ollama-telegram:latest
    depends_on:
      - ollama-server
    env_file:
      - .env
    networks:
      - yournetwork
    ports:
      - 1444:11434
networks:
  yournetwork: {}
```

**Comment by ruecat** [comment]
@alexandervnuchkov
You have to set port for telegram client as well + same network.
Try using this:
```yaml
name: ollama
services:
  ollama-server:
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    networks:
      - yournetwork
  ollama-telegram:
    restart: always
    image: ruecat/ollama-telegram:latest
    depends_on:
      - ollama-server
    env_file:
      - .env
    networks:
      - yournetwork
    ports:
      - 1444:11434
networks:
  yournetwork: {}
```
